// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omihobuxxjegxbdieolc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9taWhvYnV4eGplZ3hiZGllb2xjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3OTM0MDIsImV4cCI6MjA2MzM2OTQwMn0.3FrEg7s8n8xHfB8Qcx7BTFh5yn8gnoYe9EIhlKcN8a0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});